// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SamanaFit.Data.Context;

#nullable disable

namespace SamanaFit.Data.Migrations
{
    [DbContext(typeof(SamanaFitContext))]
    [Migration("20260425224826_AddDescripcionToObjetivos")]
    partial class AddDescripcionToObjetivos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SamanaFit.Data.Models.DetalleRutina", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int?>("Descanso")
                        .HasColumnType("int");

                    b.Property<int?>("IdEjercicio")
                        .HasColumnType("int");

                    b.Property<int?>("IdRutina")
                        .HasColumnType("int");

                    b.Property<int?>("Repeticiones")
                        .HasColumnType("int");

                    b.Property<int?>("Series")
                        .HasColumnType("int");

                    b.HasKey("IdDetalle")
                        .HasName("PK__DetalleR__E43646A5D08B34BF");

                    b.HasIndex("IdEjercicio");

                    b.HasIndex("IdRutina");

                    b.ToTable("DetalleRutina");
                });

            modelBuilder.Entity("SamanaFit.Data.Models.Ejercicio", b =>
                {
                    b.Property<int>("IdEjercicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEjercicio"));

                    b.Property<string>("GrupoMuscular")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdEjercicio")
                        .HasName("PK__Ejercici__F0E6D605D6316D58");

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("SamanaFit.Data.Models.Nivel", b =>
                {
                    b.Property<int>("IdNivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNivel"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdNivel")
                        .HasName("PK__Nivel__A7F93DEC91AE3020");

                    b.ToTable("Nivel");
                });

            modelBuilder.Entity("SamanaFit.Data.Models.Objetivo", b =>
                {
                    b.Property<int>("IdObjetivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdObjetivo"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdObjetivo")
                        .HasName("PK__Objetivo__E210F07150B145C8");

                    b.ToTable("Objetivos");
                });

            modelBuilder.Entity("SamanaFit.Data.Models.Rutina", b =>
                {
                    b.Property<int>("IdRutina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRutina"));

                    b.Property<DateOnly?>("FechaCreacion")
                        .HasColumnType("date");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdRutina")
                        .HasName("PK__Rutinas__6E34CA3D3687D11B");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("SamanaFit.Data.Models.Sexo", b =>
                {
                    b.Property<int>("IdSexo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSexo"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdSexo");

                    b.HasIndex(new[] { "Nombre" }, "UQ_Sexo_Nombre")
                        .IsUnique();

                    b.ToTable("Sexo");
                });

            modelBuilder.Entity("SamanaFit.Data.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<decimal?>("Altura")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("Edad")
                        .HasColumnType("int");

                    b.Property<int?>("IdNivel")
                        .HasColumnType("int");

                    b.Property<int?>("IdObjetivo")
                        .HasColumnType("int");

                    b.Property<int?>("IdSexo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuarios__5B65BF977DDDC54F");

                    b.HasIndex("IdNivel");

                    b.HasIndex("IdObjetivo");

                    b.HasIndex("IdSexo");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SamanaFit.Data.Models.DetalleRutina", b =>
                {
                    b.HasOne("SamanaFit.Data.Models.Ejercicio", "IdEjercicioNavigation")
                        .WithMany("DetalleRutinas")
                        .HasForeignKey("IdEjercicio")
                        .HasConstraintName("FK_DetalleRutina_Ejercicios");

                    b.HasOne("SamanaFit.Data.Models.Rutina", "IdRutinaNavigation")
                        .WithMany("DetalleRutinas")
                        .HasForeignKey("IdRutina")
                        .HasConstraintName("FK_DetalleRutina_Rutinas");

                    b.Navigation("IdEjercicioNavigation");

                    b.Navigation("IdRutinaNavigation");
                });

            modelBuilder.Entity("SamanaFit.Data.Models.Rutina", b =>
                {
                    b.HasOne("SamanaFit.Data.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Rutinas")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK_Rutinas_Usuarios");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("SamanaFit.Data.Models.Usuario", b =>
                {
                    b.HasOne("SamanaFit.Data.Models.Nivel", "IdNivelNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdNivel")
                        .HasConstraintName("FK_Usuarios_Nivel");

                    b.HasOne("SamanaFit.Data.Models.Objetivo", "IdObjetivoNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdObjetivo")
                        .HasConstraintName("FK_Usuarios_Objetivos");

                    b.HasOne("SamanaFit.Data.Models.Sexo", "IdSexoNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdSexo")
                        .HasConstraintName("FK_Usuarios_Sexo");

                    b.Navigation("IdNivelNavigation");

                    b.Navigation("IdObjetivoNavigation");

                    b.Navigation("IdSexoNavigation");
                });

            modelBuilder.Entity("SamanaFit.Data.Models.Ejercicio", b =>
                {
                    b.Navigation("DetalleRutinas");
                });

            modelBuilder.Entity("SamanaFit.Data.Models.Nivel", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SamanaFit.Data.Models.Objetivo", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SamanaFit.Data.Models.Rutina", b =>
                {
                    b.Navigation("DetalleRutinas");
                });

            modelBuilder.Entity("SamanaFit.Data.Models.Sexo", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SamanaFit.Data.Models.Usuario", b =>
                {
                    b.Navigation("Rutinas");
                });
#pragma warning restore 612, 618
        }
    }
}
